Changes in option arguments (case)
 Options changed to letters instead of full words to make it easier to use.

diff --git a/scripts/finstall b/scripts/finstall
--- a/scripts/finstall
+++ b/scripts/finstall
@@ -1,5 +1,4 @@
 #!/bin/sh
-
 ##########################################################################################
 # By Diego Cardenas "The Samedog" under GNU GENERAL PUBLIC LICENSE Version 2, June 1991
 # (www.gnu.org/licenses/old-licenses/gpl-2.0.html) e-mail: the.samedog[]gmail.com.
@@ -20,13 +19,13 @@
 # 26-06-2015: - Changed from dropbox to github, since it has better way to handle files without
 #               compromising the raw file url.
 # 30-06-2015: - Added prompts on install and uninstall to avoid PEBKAC.
-# 03-07-2015: - Added package database URL variable, fixed the placement of the "y/n" prompt for package 
+# 03-07-2015: - Added package database URL variable, fixed the placement of the "y/n" prompt for package
 #               uninstall.
 #             - Removed *some* irony from code comments so they don't hurt feelings anymore ;^).
 # 13-07-2015: - Renamed to fpackages.
 #             - Version number changed to 0.2.
 # 20-07-2015: - Added basic dep resolving.
-#             - "install" option will not try to install a package if it's already installed, that's "reinstall"'s job. 
+#             - "install" option will not try to install a package if it's already installed, that's "reinstall"'s job.
 #             - Version bumped to to 0.3 (dep resolving).
 # 11-02-2016: - Renamed to kinstall.
 #             - Version bumped to 0.3.1 (for me to track some minor shit).
@@ -46,7 +45,7 @@
 #             - Some code cleanup.
 #             - Removed "if [ ! -d $DB_FOLDER ]" since it's not needed anymore (since a while really)
 #             - Added "if [ -f /install ]" to remove it if needed
-#             - Added "if [ ! -f /tmp/scripts ]" not a mandatory update but the "mkdir: cannot create directory ‘/tmp/scripts’: File exists"
+#             - Added "if [ ! -f /tmp/scripts ]" not a mandatory update but the "mkdir: cannot create directory â€˜/tmp/scriptsâ€™: File exists"
 #               was getting on my nerves.
 #             - ping_server is now silent (it should have been silent since the beginning)
 # 20-05-2019  - Added -H 'Cache-Control: no-cache' to curl.
@@ -56,18 +55,19 @@
 # 17-11-2019  - Now you can install local downloaded packages.
 # 18-11-2019  - Added rolling release capabilities by the rrelease script (experimental)
 #             - Version bumped to 0.6
+# 24-11-2019  - Options changed to letters instead of full words to make it easier to use.
 #
 ################################# Code begins here #######################################
 
 
 ## some variables and shit
-   
+
 URL="www.dropbox.com"                                                                                # back to dropbox
 URL2="www.google.com"                                                                                # most reliable ping
 DB_URL="https://raw.githubusercontent.com/samedog/frankenpup64/master/packages_db/packages.txt"      # package database url
 DB_FOLDER="/var/fpackages"                                                                           # installed packages folder
 DB_LOCATION="$DB_FOLDER/packages.txt"                                                                # databse location on disk
-VERSION="0.6.0"
+VERSION="0.6.1"
 
 ### function to ping google.com to check if we are (or not) connected to the internet
 
@@ -87,11 +87,11 @@ ping_server(){
 search_package(){
     SEARCH="$1"
     if [ -f "$SEARCH" ];then
-    	echo "-----------------------------------------"
-		echo "Local package install..."
-		echo "-----------------------------------------"
-		return 3
-	elif [ ! -f "DB_LOCATION" ]; then
+        echo "-----------------------------------------"
+        echo "Local package install..."
+        echo "-----------------------------------------"
+        return 3
+    elif [ ! -f "DB_LOCATION" ]; then
         db_download 1
     fi
     RESULT=$(cat $DB_LOCATION | grep -i $SEARCH)
@@ -116,21 +116,21 @@ search_package(){
 
 ### function to download and update the package list "database" ######################################
 db_download(){
-	SILENT="$1"
+    SILENT="$1"
     CON=$(ping_server)
     if [ $? -ne 2 ]; then   ## check if we are connected to the internet
         if [ ! -z "$SILENT" ];then
-			curl -H 'Cache-Control: no-cache' -s -o "$DB_LOCATION" "$DB_URL"
-			if [ $? != 0 ]; then
-				echo 'Something went wrong, error code: 1'
-			fi
+            curl -H 'Cache-Control: no-cache' -s -o "$DB_LOCATION" "$DB_URL"
+            if [ $? != 0 ]; then
+                echo 'Something went wrong, error code: 1'
+            fi
         else
-			curl -H 'Cache-Control: no-cache' --progress-bar -o "$DB_LOCATION" "$DB_URL"
-			if [ $? -eq 0 ]; then
-			    echo 'Package "database" upgraded successfully'
-			else
-				echo 'Something went wrong, error code: 1'
-			fi
+            curl -H 'Cache-Control: no-cache' --progress-bar -o "$DB_LOCATION" "$DB_URL"
+            if [ $? -eq 0 ]; then
+                echo 'Package "database" upgraded successfully'
+            else
+                echo 'Something went wrong, error code: 1'
+            fi
         fi
     else
         echo "no internet connection or 100% package loss"
@@ -147,56 +147,56 @@ install(){
     if [ $? -eq 3 ]; then
         CHNAME=$(echo $PACK | cut -d'-' -f1 2>/dev/null)
         CNAME=$(echo $PACK | sed "s/.fxz//" 2>/dev/null)
-        
+
         ## is package installed?
         if [ -f "$DB_FOLDER/$CNAME" ]; then
             echo "Package already installed"
             exit
         fi
-        
-		LOCATION="/tmp/$NAME"
-		echo "-----------------------------------------"
-		echo "Installing package..."
-		echo "-----------------------------------------"
-		cp -rf $PACK /tmp/$PACK
-		flag=$(pgrep -x "jwm")
-		cd /tmp
-		tar xf "$PACK"
-		if [ $? -eq 0 ]; then
-			rm -rf "$PACK"
-			echo "-----------------------------------------"
-			echo "Looking for custom install script..."
-			if [ -f /tmp/$CNAME/install ]; then
-				echo "-----------------------------------------"
-				echo "executing custom install script..."
-				/tmp/$CNAME/install
-				if [ $? -eq 0 ]; then
-					rm -rf /tmp/$CNAME/install
-					rm -rf /tmp/$CNAME
-					echo "-----------------------------------------"
-					if [ ! -z "$flag" ]; then
-						fixmenus
-						jwm -reload
-					fi
-					echo "Done"
-		if [ -f /install ]; then
-			rm -rf /install
-		fi
-				else
-					echo 'Something went wrong, error code: 4'
-				fi
-			else
-				echo "" > "$DB_FOLDER/$CNAME"
-				rm -rf /tmp/$CNAME
-				if [ ! -z "$flag" ]; then
-					fixmenus
-					jwm -reload
-				fi
-				echo "Done"
-			fi
-		else
-			echo 'Something went wrong, error code: 2'
-		fi
+
+        LOCATION="/tmp/$NAME"
+        echo "-----------------------------------------"
+        echo "Installing package..."
+        echo "-----------------------------------------"
+        cp -rf $PACK /tmp/$PACK
+        flag=$(pgrep -x "jwm")
+        cd /tmp
+        tar xf "$PACK"
+        if [ $? -eq 0 ]; then
+            rm -rf "$PACK"
+            echo "-----------------------------------------"
+            echo "Looking for custom install script..."
+            if [ -f /tmp/$CNAME/install ]; then
+                echo "-----------------------------------------"
+                echo "executing custom install script..."
+                /tmp/$CNAME/install
+                if [ $? -eq 0 ]; then
+                    rm -rf /tmp/$CNAME/install
+                    rm -rf /tmp/$CNAME
+                    echo "-----------------------------------------"
+                    if [ ! -z "$flag" ]; then
+                        fixmenus
+                        jwm -reload
+                    fi
+                    echo "Done"
+                    if [ -f /install ]; then
+                        rm -rf /install
+                    fi
+                else
+                    echo 'Something went wrong, error code: 4'
+                fi
+            else
+                echo "" > "$DB_FOLDER/$CNAME"
+                rm -rf /tmp/$CNAME
+                if [ ! -z "$flag" ]; then
+                    fixmenus
+                    jwm -reload
+                fi
+                echo "Done"
+            fi
+        else
+            echo 'Something went wrong, error code: 2'
+        fi
 
     elif [ $? -eq 0 ]; then
         echo "No package \"$PACK\" found"
@@ -205,14 +205,14 @@ install(){
         PURL=$(cat $DB_LOCATION | cut -d'>' -f2 | grep -i $PACK | cut -d' ' -f2 2>/dev/null)
         CHNAME=$(echo $NAME | cut -d'-' -f1 2>/dev/null)
         CNAME=$(echo $NAME | sed "s/.fxz//" 2>/dev/null)
-        DEPS=$(cat $DB_LOCATION | grep -i $PURL | cut -d'>' -f4 2>/dev/null) 
+        DEPS=$(cat $DB_LOCATION | grep -i $PURL | cut -d'>' -f4 2>/dev/null)
 
         ## is package installed?
         if [ -f "$DB_FOLDER/$CNAME" ]; then
             echo "Package already installed"
             exit
         fi
-        
+
         ## NOASK is the default dep resolver option
         if [ ! -z "$NOASK" ]; then
             CHECK="y"
@@ -233,10 +233,10 @@ install(){
                         EACH=$(echo "$DEPS" | cut -d' ' -f$c)
                         if [ ! -z "$EACH" ]; then
                             echo "\"$EACH\""
-							if [ -f "$DB_FOLDER/$EACH" ]; then
-								echo "Package already installed"
-							else
-                                finstall install "$EACH" "yes"
+                            if [ -f "$DB_FOLDER/$EACH" ]; then
+                                echo "Package already installed"
+                            else
+                                finstall i "$EACH" "yes"
                             fi
                         fi
                     done
@@ -249,7 +249,7 @@ install(){
             echo "-----------------------------------------"
             pcurl "$LOCATION" "http://$URL/$PURL"
             if [ $? -eq 0 ]; then
-		    flag=$(pgrep -x "jwm")
+            flag=$(pgrep -x "jwm")
                 cd /tmp
                 tar xf "$NAME"
                 if [ $? -eq 0 ]; then
@@ -269,9 +269,9 @@ install(){
                                 jwm -reload
                             fi
                             echo "Done"
-			    if [ -f /install ]; then
-			    	rm -rf /install
-			    fi
+                            if [ -f /install ]; then
+                                rm -rf /install
+                            fi
                         else
                             echo 'Something went wrong, error code: 4'
                         fi
@@ -302,7 +302,7 @@ uninstall(){
     PACK="$1"
     SEARCH=$(ls $DB_FOLDER | grep -i $PACK)
     if [ ! -z "$SEARCH" ]; then
-		NAME=$(cat $DB_LOCATION | cut -d'>' -f1 | grep -i $PACK | cut -d' ' -f1 | cut -d'/' -f2)
+        NAME=$(cat $DB_LOCATION | cut -d'>' -f1 | grep -i $PACK | cut -d' ' -f1 | cut -d'/' -f2)
         CNAME=$(echo $NAME | sed "s/.fxz//")
         DEPS=$(cat $DB_LOCATION | grep -i $NAME | cut -d'>' -f4 )
         echo "$SEARCH found"
@@ -324,8 +324,8 @@ uninstall(){
     else
         echo "No package \"$PACK\" found, are you sure it's installed?"
     fi
-    
-    
+
+
 }
 
 ### function to upgrade scripts, this is just a set of multiple wget and will get 'em regardless if they are up to date on the machine or not
@@ -342,31 +342,31 @@ supdate(){
         curl -H 'Cache-Control: no-cache' -L --progress-bar -O "https://raw.githubusercontent.com/samedog/frankenpup64/master/scripts/rreleases"
         curl -H 'Cache-Control: no-cache' -L --progress-bar -O "https://raw.githubusercontent.com/samedog/frankenpup64/master/scripts/night-mode-switch"
         if [ $? -eq 0 ]; then
-			echo "making executable..."
-			chmod -R 1777 ./*
-			echo "Copying to my-applications..."
-			cp -rf /tmp/scripts/* /root/my-applications/bin/
-			echo "Done"
-			exec rm -rf /tmp/finstall-tmp
+            echo "making executable..."
+            chmod -R 1777 ./*
+            echo "Copying to my-applications..."
+            cp -rf /tmp/scripts/* /root/my-applications/bin/
+            echo "Done"
+            exec rm -rf /tmp/finstall-tmp
         fi
     else
         echo "No internet connection, 100% package loss or server offline"
     fi
 }
 rolling_release(){
-	rreleases
+    rreleases
 }
 
 ### initialization and shit
 case "$1" in
-    install)
+    i)
         install "$2" "$3"
     ;;
-    reinstall)
+    ri)
         uninstall "$2"
         install "$2" "yes"
     ;;
-    search)
+    s)
         search_package "$2"
         if [ $? -eq 0 ]; then
             echo "No package \"$2\" found"
@@ -374,17 +374,17 @@ case "$1" in
             exit
         fi
     ;;
-    upgrade)
-		rolling_release
+    u)
+        rolling_release
     ;;
-    db-update)
+    dbu)
         echo "updating package list..."
         db_download
     ;;
     uninstall)
         uninstall "$2"
     ;;
-    script-update)
+    su)
         cp -rf /root/my-applications/bin/finstall /tmp/finstall-tmp
         chmod 1777 /tmp/finstall-tmp
         exec /tmp/finstall-tmp supdate-tmp
@@ -395,39 +395,39 @@ case "$1" in
         fi
         killall kill finstall 2>/dev/null
         supdate
-	supdate
-        exec /root/my-applications/bin/finstall finish
+        /root/my-applications/bin/finstall finish
+        supdate
     ;;
     finish)
     #hope this works
-        exec rm -rf /tmp/scripts/*
-        exec rm -rf /tmp/scripts
+        rm -rf /tmp/scripts/*
+        rm -rf /tmp/scripts
     ;;
-    list)
+    l)
         if [ ! -f "$DB_LOCATION" ]; then
             db_download
         fi
         echo "$(cat "$DB_LOCATION" | cut -d'>' -f 1,3)"
     ;;
-    version)
-		echo "$VERSION"
-	;;
+    v)
+    echo "$VERSION"
+    ;;
     *)
     echo "This small script was created to handle software compiled and tested for frankenpup64
 
-Usage: finstall {install|reinstall|upgrade|uninstall|search|db-update|script-update|list|version}
+Usage: finstall {i|ri|u|ui|s|dbu|su|l|v}
 
-install:          Install a package.
-                    ex: finstall install gimp or finstall install gimp.txz for a local package
-reinstall:        Reinstalls a package.
-upgrade:          Install system updates.
-uninstall:        Uninstalls a package.
-search:           Search a package.
-                    ex: finstall search gimp
-db-update:        Updates the package database.
-script-update:      Updates scripts (create fxz and finstall).
-list:             List all packages in database.
-version:          Prints script version
+i:          Install a package.
+               ex: finstall i gimp or finstall i gimp.txz for a local package
+ri:        Reinstalls a package.
+u:         Install system updates.
+ui:        Uninstalls a package.
+s:         Search a package.
+               ex: finstall search gimp
+dbu:       Updates the package database.
+su:        Updates frankenpup scripts.
+l:         List all packages in database.
+v:         Prints script version
 "
-    
+
 esac
