Changes to comply with finstall
- Less verbosity.
- Fixed some code to make it actually work with finstall.
- package repo will remain at frankenpuplinux.com instad of dropbox
- Added "-L"  just in case we need to follow a redirect
- "#TODO Add exit at this point if this previous step fails" is now done.

diff --git a/scripts/pcurl b/scripts/pcurl
--- a/scripts/pcurl
+++ b/scripts/pcurl
@@ -1,15 +1,23 @@
-#!/bin/bash
+#!/bin/sh
 #title           :pcurl.sh
 #description     :This script will download a file in segments.
-#author		 :Phil Rumble prumble@au1.ibm.com
+#author		     :Phil Rumble prumble@au1.ibm.com
 #date            :20120202
 #version         :0.1    
-#usage		 :bash pcurl.sh url
 #notes           :Install curl to use this script.
+# Edited by samedog for use with frankenpupLinux finstall
+# usage		     :bash pcurl file url
+#Changelog:
+# 09-05-2019  - Less verbosity.
+#             - Fixed some code to make it actually work with finstall.
+#             - package repo will remain at frankenpuplinux.com instad of dropbox
+#             - Added -L just in case we need to follow a redirect
+#             - "#TODO Add exit at this point if this previous step fails" is now done.
+############################# actual code begins here, lol ######################################
+debug() { echo "DEBUG: $*" > /dev/null; }
 
-
-debug() { echo "DEBUG: $*" >&2; }
-
+o=$1
+u=$2
 
 waitall() { # PID...
   ## Wait for children to exit and indicate whether all exited with 0 status.
@@ -39,7 +47,7 @@ waitall() { # PID...
 URL=$1
 FILENAME=`basename $URL`
 
-echo "Downloading ${URL}"
+echo "Downloading $u"
 
 #curl -s -I ${URL} 
 #FILESIZE=`curl -s -I ${URL} | cut -s -f 2 -d ':' | tail -2 | xargs echo | awk '{print $1}'`
@@ -49,7 +57,7 @@ echo "Downloading ${URL}"
 #echo ${FILESIZE}
 
 FILESIZE_TXT="./FILESIZE.txt"
-curl -s -I ${URL} > ${FILESIZE_TXT}
+curl -L -s -I "$u" > ${FILESIZE_TXT}
 i="0"
 
 FILESIZE="0"
@@ -75,14 +83,17 @@ done < ${FILESIZE_TXT}
 rm -f ${FILESIZE_TXT}
 
 #TODO Add exit at this point if this previous step fails.
+# done by samedog
+if [ $? != 0 ]; then
+    exit 1
+fi
+#echo "flsize is ${FILESIZE} bytes"
 
-echo "flsize is ${FILESIZE} bytes"
-
-MAX_SEGMENTS=10
+MAX_SEGMENTS=5
 
 SEGMENT_SIZE=`expr $((${FILESIZE} / ${MAX_SEGMENTS}))`
 
-echo "SEGMENT_SIZE is set to ${SEGMENT_SIZE}"
+#echo "SEGMENT_SIZE is set to ${SEGMENT_SIZE}"
 
 START_SEG=0;
 END_SEG=${SEGMENT_SIZE}
@@ -91,14 +102,14 @@ for i in $(eval echo {1..${MAX_SEGMENTS}})
 do
 	if [ "$i" !=  "$MAX_SEGMENT" ]
 	then 
-		curl -s --range ${START_SEG}-${END_SEG} -o ${FILENAME}.part${i} ${URL} &
+		curl -L --progress-bar --range ${START_SEG}-${END_SEG} -o "$o".part${i} "$u" &
 		pids="$pids $!"
 	else
-		curl -s --range ${START_SEG}- -o ${FILENAME}.part${i} ${URL} &
+		curl -L --progress-bar --range ${START_SEG}- -o "$o".part${i} "$u" &
 		pids="$pids $!"
 	fi
-	echo "Start = ${START_SEG}"
-	echo "End = ${END_SEG}"
+	#echo "Start = ${START_SEG}"
+	#echo "End = ${END_SEG}"
 	START_SEG=$((${END_SEG}+1))
 	END_SEG=$((${START_SEG}+${SEGMENT_SIZE}))
 done
@@ -107,22 +118,24 @@ done
 	#pids="$pids $!"
 
 	waitall $pids
-	echo "Download of segments is completed"
+	#echo "Download of segments is completed"
 
 i=1
 for i in $(eval echo {1..${MAX_SEGMENTS}})
 do
-	if [ "$i" == 1 ]
+	if [ "$i" -eq 1 ]
 	then
 		#echo "building segment:${i}"
-		cat ${FILENAME}.part${i} > ${FILENAME}
+		#cat  "$o".part${i}
+		cat "$o".part${i} > "$o"
 	else
 		#echo "building segment:${i}"
-		cat ${FILENAME}.part${i} >> ${FILENAME}
+		#cat  "$o".part${i}
+		cat "$o".part${i} >> "$o"
 	fi
 done
 for i in $(eval echo {1..${MAX_SEGMENTS}})
 do
-	rm -f ${FILENAME}.part${i} 
+	rm -f "$o".part${i} 
 done
 echo "Download of ${FILENAME} is complete"
